#!/bin/bash
mkdir -p $HOME/.spotify/{config,cache,dbus}
chmod 700 $HOME/.spotify
chmod 777 $HOME/.spotify/*
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $HOME/.spotify/xauth nmerge -
exec docker run \
      --rm \
      -v /etc/localtime:/etc/localtime:ro \
      -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
      -e DISPLAY \
      -v $HOME/.spotify/config:/home/spotify/.config/spotify \
      -v $HOME/.spotify/cache:/home/spotify/.cache/spotify \
      -v $HOME/.spotify/dbus:/tmp/dbus \
      -v $HOME/.spotify/xauth:/home/spotify/.Xauthority:ro \
      -v /run/user/$UID/pulse/native:/run/pulse/native:ro \
      -e PULSE_SERVER=/run/pulse/native \
      -e QT_X11_NO_MITSHM=1 \
      --name spotify \
      spotify
